name: cms-hosting

services:
  next:
    image: ${NEXT_IMAGE:-cms-hosting-next:local}
    build:
    # set context to project root and path to Dockerfile because the Dockerfile is in the docker/app directory
      context: ..
      dockerfile: docker/app/Dockerfile
    env_file:
      - ../.env
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    expose:
      - "3000"
    restart: unless-stopped

  reverse-proxy:
    image: ${NGINX_IMAGE:-cms-hosting-nginx:local}
    build:
    #context is relative to /docker directory
      context: ./nginx
    depends_on:
      - next
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-webroot:/var/www/certbot
    environment:
      - DOMAIN=${DOMAIN:-example.com}
    restart: unless-stopped

  certbot:
    #context is relative to /docker directory
    image: certbot/certbot:latest
    depends_on:
      - reverse-proxy
    environment:
      - DOMAINS=${DOMAINS:-example.com}
      - SSL_EMAIL=${SSL_EMAIL:-admin@example.com}
      - WEBROOT_PATH=/var/www/certbot
      - STAGING=${STAGING:-false}
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-webroot:/var/www/certbot
      - ./certbot/renew.sh:/opt/certbot/renew.sh:ro
    entrypoint: ["/bin/sh", "/opt/certbot/renew.sh"]
    command: ["renew"]
    restart: unless-stopped

volumes:
  certbot-etc:
  certbot-var:
  certbot-webroot:
