name: Test - Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted]  # match full label set
    steps:
      - run: |
          echo "âœ… Runner is working!"
          hostname
          uname -a
          docker --version
